# Generated by Django 2.2.15 on 2020-08-21 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200821_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=None)),
                ('completion_date', models.DateField()),
                ('grade', models.CharField(max_length=200)),
                ('course_level', models.CharField(choices=[('university', 'University'), ('other', 'Other')], default='university', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ALevel',
        ),
        migrations.DeleteModel(
            name='GCSE',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
