# Generated by Django 2.2.15 on 2020-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200821_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_level',
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('year1', 'Year 1'), ('year2', 'Year 2'), ('year3', 'Year 3'), ('year4', 'Year 4'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
