# Generated by Django 2.2.15 on 2020-08-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200821_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
